import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#279ec6] to-[#012b5d]">
        <div className="flex h-screen items-center justify-center">
          <div className="rounded-lg bg-white p-6 shadow-lg">
            <h2 className="mb-4 text-center text-2xl font-bold">
              Paste url to be shortened
            </h2>
            <div className="flex items-center rounded-lg border border-gray-400 px-4 py-2">
              <input
                type="text"
                className="w-full py-2 px-4 leading-tight text-gray-700 focus:outline-none"
                placeholder="Enter URL here"
              />
              <button className="ml-2 rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700">
                Shorten
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
